version: "3"
services:
  data-seed:
    container_name: data-seed
    command: bash -c "python trip_seed.py"
    image: data-seed
    build: ./data-seed
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=${MONGO_DB}
      - API_OLHO_VIVO_TOKEN=${API_OLHO_VIVO_TOKEN}
    links:
      - mongo
    depends_on:
      - "mongo"

  webapp:
    container_name: webapp
    image: webapp
    build: ./webapp
    depends_on:
      - "server"

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /tmp/microservices-example-node/data:/data/db

  proxy:
    image: nginx_balancer
    build: ./proxy
    ports:
      - 80:80
    depends_on:
      - "server"
      - "webapp"
