version: "3"
services:
  server:
    container_name: microservices-example-node
    restart: always
    image: microservices-example-node:prod
    build: ./nodejs-api
    environment:
      - API_OLHO_VIVO_TOKEN=${API_OLHO_VIVO_TOKEN}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=${MONGO_DB}
      - PORT=9000
    links:
      - mongo
    depends_on:
      - "data-seed"
      - "mongo"
