apiVersion: v1
kind: Service
metadata:
  namespace: microservices-example
  labels:
    app: mongo
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017