apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-example
  labels:
    service: webapp
  name: webapp
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
        track: stable
    spec:
      containers:
      - image: webapp
        imagePullPolicy: Never
        name: webapp
        resources: {}
      restartPolicy: Always
status: {}
