apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-example
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo-local
        name: mongo
        imagePullPolicy: Never
        ports:
        - containerPort: 27017
      restartPolicy: Always
          
status: {}
